/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stoktakip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ikbal
 */
public class Urun extends javax.swing.JFrame {

    String adres = "jdbc:derby://localhost:1527/StokData";
    String kullanici = "eqbal";
    String sifre = "123";

    /**
     * Creates new form UrunEkle
     */
    public Urun() {
        initComponents();
        TabloDoldurURUN();
        TabloDoldurMUSTERI();
    }

    private void TabloDoldurMUSTERI() {
        jTableMusteri.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    " ID", "MÜŞTERİ ADI", "SOYADI", "TELEFON NO", "EMAİL"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        try {
            Connection con = DriverManager.getConnection(adres, kullanici, sifre);
            Statement sorgu = con.createStatement();
            ResultSet sonuc = sorgu.executeQuery("SELECT * FROM MUSTERI");
            int sutun = sonuc.getMetaData().getColumnCount();
            while (sonuc.next()) {
                Object[] satir = new Object[sutun];
                for (int i = 1; i <= sutun; i++) {
                    satir[i - 1] = sonuc.getObject(i);
                }
                ((DefaultTableModel) jTableMusteri.getModel()).insertRow(sonuc.getRow() - 1, satir);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Bağlanti Hatası!");
        }

    }

    private void TabloDoldurURUN() {
        jTableUrun.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID", "URUN ADI", "ADET", "KATEGORI", "AÇIKLAMA"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        try {
            Connection con = DriverManager.getConnection(adres, kullanici, sifre);
            Statement sorgu = con.createStatement();
            ResultSet sonuc = sorgu.executeQuery("SELECT * FROM URUN_BILGILERI");
            int sutun = sonuc.getMetaData().getColumnCount();
            while (sonuc.next()) {
                Object[] satir = new Object[sutun];
                for (int i = 1; i <= sutun; i++) {
                    satir[i - 1] = sonuc.getObject(i);
                }
                ((DefaultTableModel) jTableUrun.getModel()).insertRow(sonuc.getRow() - 1, satir);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Bağlanti Hatası!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItemAnaEkrana = new javax.swing.JMenuItem();
        jMenuItemKapat = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSpinnerUrunAdet = new javax.swing.JSpinner();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUrunAdi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        StokEkle = new javax.swing.JButton();
        StokYenile = new javax.swing.JButton();
        jTextFieldUrunAciklama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        StokSil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUrun = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMusteri = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jButtonYeniMusteri = new javax.swing.JButton();
        jButtonMusteriEkle = new javax.swing.JButton();
        jButtonMusteriGuncelle = new javax.swing.JButton();
        jButtonSilMusteri = new javax.swing.JButton();

        jMenuItemAnaEkrana.setText("Ana Ekrana Geri Dön");
        jMenuItemAnaEkrana.setActionCommand("Ana Ekrana Geri Dön");
        jMenuItemAnaEkrana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnaEkranaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemAnaEkrana);

        jMenuItemKapat.setText("Kapat");
        jMenuItemKapat.setActionCommand("Kapat");
        jMenuItemKapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKapatActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemKapat);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setComponentPopupMenu(jPopupMenu1);
        jPanel1.setInheritsPopupMenu(true);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Araba", "Telefon", "Ev Eşyası", "Elektronik Cihaz", "TV", "Temizlik Malzemesi", "Yemek", "İçecek", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("ID:");

        jLabel6.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel6AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTextFieldUrunAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUrunAdiActionPerformed(evt);
            }
        });

        jLabel1.setText("Ürün Adı");

        jLabel2.setText("Adet:");

        StokEkle.setText("Stok Ekle");
        StokEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StokEkleActionPerformed(evt);
            }
        });

        StokYenile.setText("Yenile");
        StokYenile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StokYenileActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stoktakip/urunekle.png"))); // NOI18N

        jLabel3.setText("Ürün Açıklaması");

        jLabel4.setText("Kategori:");

        StokSil.setText("Sil");
        StokSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StokSilActionPerformed(evt);
            }
        });

        jTableUrun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "URUN ADI", "ADET", "KATEGORI", "AÇIKLAMA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableUrun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableUrunMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUrun);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StokSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(StokYenile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StokEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldUrunAdi)
                        .addComponent(jTextFieldUrunAciklama)
                        .addComponent(jSpinnerUrunAdet)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldUrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jSpinnerUrunAdet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jTextFieldUrunAciklama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addComponent(StokEkle)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(StokYenile)
                            .addGap(18, 18, 18)
                            .addComponent(StokSil))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addGap(28, 28, 28))))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Urun", jPanel1);

        jLabel8.setText("ID:");

        jLabel10.setText("Müşteri Adı:");

        jLabel11.setText("Soyadı:");

        jLabel12.setText("Telefon No:");

        jLabel13.setText("Email:");

        jTableMusteri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " ID", "MÜŞTERİ ADI", "SOYADI", "TELEFON NO", "EMAİL", "CINSIYETI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMusteri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableMusteriMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTableMusteri);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stoktakip/musteri ekle.png"))); // NOI18N

        jCheckBox1.setText("Erkek");

        jCheckBox2.setText("Kadın");

        jLabel15.setText("Cinsiyet:");

        jButtonYeniMusteri.setText("Yeni");

        jButtonMusteriEkle.setText("Ekle");
        jButtonMusteriEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMusteriEkleActionPerformed(evt);
            }
        });

        jButtonMusteriGuncelle.setText("Güncelle");
        jButtonMusteriGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMusteriGuncelleActionPerformed(evt);
            }
        });

        jButtonSilMusteri.setText("Sil");
        jButtonSilMusteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSilMusteriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox2)
                        .addGap(14, 14, 14))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonMusteriEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonYeniMusteri, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonMusteriGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSilMusteri, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonYeniMusteri)
                    .addComponent(jButtonMusteriEkle)
                    .addComponent(jButtonMusteriGuncelle)
                    .addComponent(jButtonSilMusteri))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Müşteri", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUrunAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUrunAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUrunAdiActionPerformed

    private void StokEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StokEkleActionPerformed
        String URUN_ADI = jTextFieldUrunAdi.getText();
        String ADET = jSpinnerUrunAdet.getValue().toString();
        String KATEGORI = jComboBox1.getSelectedItem().toString();
        String ACIKLAMA = jTextFieldUrunAciklama.getText();

        if (jTextFieldUrunAdi.getText().equals("") || ADET.toString().equals("") || KATEGORI.toString().equals("") || ACIKLAMA.toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Boş alan bırakılamaz!",
                    "warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String sorgu = "INSERT INTO URUN_BILGILERI (URUN_ADI, ADET,KATEGORI,ACIKLAMA)"
                    + "VALUES ( '" + URUN_ADI + "', '" + ADET + "','" + KATEGORI + "','" + ACIKLAMA + "')";
            try {
                Connection con = DriverManager.getConnection(adres, kullanici, sifre);
                Statement st = con.createStatement();
                st.execute(sorgu);
                con.close();
                TabloDoldurURUN();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            JOptionPane.showMessageDialog(null, "Kayıt Başarıyla Tamamlandı.");
        }
     }//GEN-LAST:event_StokEkleActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void StokYenileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StokYenileActionPerformed
        jLabel6.setText(null);
        jTextFieldUrunAdi.setText(null);
        jSpinnerUrunAdet.setValue(0);
        jComboBox1.setSelectedItem(null);
        jTextFieldUrunAciklama.setText(null);
    }//GEN-LAST:event_StokYenileActionPerformed

    private void StokSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StokSilActionPerformed
        int secilenSatir = jTableUrun.getSelectedRow();
        if (secilenSatir == -1) {
            JOptionPane.showMessageDialog(null, "Lutfen bir secim yapiniz!");
        } else {
            int onay = JOptionPane.showConfirmDialog(null, "Emin misiniz?");
            if (onay == 0) {
                String ID = jTableUrun.getValueAt(secilenSatir, 0).toString();

                try {
                    Connection con = DriverManager.getConnection(adres, kullanici, sifre);
                    Statement sorgu = con.createStatement();
                    sorgu.executeUpdate("DELETE FROM URUN_BILGILERI WHERE ID =" + ID);
                    con.close();
                    TabloDoldurURUN();
                } catch (SQLException ex) {
                    Logger.getLogger(Personel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }     }//GEN-LAST:event_StokSilActionPerformed

    private void jLabel6AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel6AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6AncestorAdded

    private void jTableUrunMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUrunMousePressed
        int secilenSatir = jTableUrun.getSelectedRow();

        String ID = jTableUrun.getValueAt(secilenSatir, 0).toString();
        String URUN_ADI = jTableUrun.getValueAt(secilenSatir, 1).toString();
        String ADET = jTableUrun.getValueAt(secilenSatir, 2).toString();
        String KATEGORI = jTableUrun.getValueAt(secilenSatir, 3).toString();
        String ACIKLAMA = jTableUrun.getValueAt(secilenSatir, 4).toString();

        jLabel6.setText(ID);
        jTextFieldUrunAdi.setText(URUN_ADI);
//        jSpinnerUrunAdet.setText(ADET);
//        jComboBox1.setText(KATEGORI);
//        jTextFieldUrunAciklama.setText(ACIKLAMA);

     }//GEN-LAST:event_jTableUrunMousePressed

    private void jButtonMusteriGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMusteriGuncelleActionPerformed
        int secilenSatir = jTableMusteri.getSelectedRow();
        if (secilenSatir == -1) {
            JOptionPane.showMessageDialog(null, "Lutfen bir secim yapiniz!");
        } else {
            String ID = jTableMusteri.getValueAt(secilenSatir, 0).toString();
            String ADI = jTextField1.getText();
            String SOYAD = jTextField2.getText();
            String TELEFON = jTextField3.getText();
            String EMAIL = jTextField4.getText();

            String sorgu = "UPDATE  MUSTERI SET "
                    + "ADI = '" + ADI + "',"
                    + "SOYAD = '" + SOYAD + "',"
                    + "TELEFON = '" + TELEFON + "',"
                    + "EMAIL = '" + EMAIL + " ' "
                    + "WHERE ID = " + ID;
            try {
                Connection con = DriverManager.getConnection(adres, kullanici, sifre);
                Statement st = con.createStatement();
                st.executeUpdate(sorgu);
                con.close();
                TabloDoldurMUSTERI();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Guncellenmedi");
            }
            JOptionPane.showMessageDialog(null, "Guncelleme Başarıyla Tamamlandı.");

        }    }//GEN-LAST:event_jButtonMusteriGuncelleActionPerformed

    private void jButtonMusteriEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMusteriEkleActionPerformed
        String ADI = jTextField1.getText();
        String SOYAD = jTextField2.getText();
        String TELEFON = jTextField3.getText();
        String EMAIL = jTextField4.getText();

        if (jTextField1.getText().equals("") || jTextField2.getText().equals("") || jTextField3.getText().equals("") || jTextField4.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Boş alan bırakılamaz!",
                    "warning", JOptionPane.WARNING_MESSAGE);
        } else {

            String sorgu = "INSERT INTO MUSTERI (ADI, SOYAD,TELEFON,EMAIL)"
                    + "VALUES ( '" + ADI + "', '" + SOYAD + "','" + TELEFON + "','" + EMAIL + "')";
            try {
                Connection con = DriverManager.getConnection(adres, kullanici, sifre);
                Statement st = con.createStatement();
                st.execute(sorgu);
                con.close();
                TabloDoldurMUSTERI();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            JOptionPane.showMessageDialog(null, "Kayıt Başarıyla Tamamlandı.");

        }    }//GEN-LAST:event_jButtonMusteriEkleActionPerformed

    private void jTableMusteriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMusteriMousePressed
        int secilenSatir = jTableMusteri.getSelectedRow();
        System.out.println(secilenSatir);

        String ID = jTableMusteri.getValueAt(secilenSatir, 0).toString();
        String ADI = jTableMusteri.getValueAt(secilenSatir, 1).toString();
        String SOYAD = jTableMusteri.getValueAt(secilenSatir, 2).toString();
        String TELEFON = jTableMusteri.getValueAt(secilenSatir, 3).toString();
        String EMAIL = jTableMusteri.getValueAt(secilenSatir, 4).toString();

        jLabel9.setText(ID);
        jTextField1.setText(ADI);
        jTextField2.setText(SOYAD);
        jTextField3.setText(TELEFON);
        jTextField4.setText(EMAIL);    }//GEN-LAST:event_jTableMusteriMousePressed

    private void jButtonSilMusteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSilMusteriActionPerformed
        int secilenSatir = jTableMusteri.getSelectedRow();
        if (secilenSatir == -1) {
            JOptionPane.showMessageDialog(null, "Lutfen bir secim yapiniz!");
        } else {
            int onay = JOptionPane.showConfirmDialog(null, "Emin misiniz?");
            if (onay == 0) {
                String ID = jTableMusteri.getValueAt(secilenSatir, 0).toString();

                try {
                    Connection con = DriverManager.getConnection(adres, kullanici, sifre);
                    Statement sorgu = con.createStatement();
                    sorgu.executeUpdate("DELETE FROM MUSTERI WHERE ID =" + ID);
                    con.close();
                    TabloDoldurMUSTERI();
                } catch (SQLException ex) {
                    Logger.getLogger(Personel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonSilMusteriActionPerformed

    private void jMenuItemAnaEkranaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnaEkranaActionPerformed
        AnaEkran f1 = new AnaEkran();
                    f1.setVisible(true);
                     dispose();
    }//GEN-LAST:event_jMenuItemAnaEkranaActionPerformed

    private void jMenuItemKapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKapatActionPerformed
                     dispose();
    }//GEN-LAST:event_jMenuItemKapatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Urun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StokEkle;
    private javax.swing.JButton StokSil;
    private javax.swing.JButton StokYenile;
    private javax.swing.JButton jButtonMusteriEkle;
    private javax.swing.JButton jButtonMusteriGuncelle;
    private javax.swing.JButton jButtonSilMusteri;
    private javax.swing.JButton jButtonYeniMusteri;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItemAnaEkrana;
    private javax.swing.JMenuItem jMenuItemKapat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerUrunAdet;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableMusteri;
    private javax.swing.JTable jTableUrun;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldUrunAciklama;
    private javax.swing.JTextField jTextFieldUrunAdi;
    // End of variables declaration//GEN-END:variables
}
